In [2]:
import pandas as pd

In [3]:
info = {
       "Name":["Rahul","Ram","Krishna"],
       "Age":[23,12,23]
}

df=pd.DataFrame(info)
print(df)

      Name  Age
0    Rahul   23
1      Ram   12
2  Krishna   23

In [4]:
df

      Name  Age
0    Rahul   23
1      Ram   12
2  Krishna   23

In [5]:
s=pd.Series([1,2,3,4,"abc"],index=["A","B","C","D","5"])
print(s)
print(s[0])

A      1
B      2
C      3
D      4
5    abc
dtype: object
1

C:\Users\kkris\AppData\Local\Temp\ipykernel_21716\2630960715.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

In [6]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,10])
print(s1+s2)
s1[0]=10
print(s1+s2)
Changed_s1=s1.drop(0)
print(Changed_s1)

0     7
1     9
2    11
3    13
4    15
dtype: int64
0    16
1     9
2    11
3    13
4    15
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
inf={
    "Name":["Ram","Shyam","Radha"],
    "Age":[23,43,14],
    "CGPA":[9.5,8.9,7.8]
}
df=pd.DataFrame(inf)
print(df)
print(df,type(df))
print(df.index)
print(df.columns)

    Name  Age  CGPA
0    Ram   23   9.5
1  Shyam   43   8.9
2  Radha   14   7.8
    Name  Age  CGPA
0    Ram   23   9.5
1  Shyam   43   8.9
2  Radha   14   7.8 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [8]:
import numpy as np

In [9]:
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [10]:
df=pd.read_csv("globalAirQuality.csv")
print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [11]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [20]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [35]:
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [42]:
df.iloc[2]

timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object

In [68]:
cities=df["city"].copy()
cities[0]="New york"
print(cities)

0        New york
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [73]:
df[(df["aqi"]>100) & (df["temperature"]>30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [83]:
df.query("aqi>100 & temperature>30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]