In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/kaggle/input/datasets/rkrohitkumar/imbd-dataset-csv/IMDB Dataset.csv")

In [4]:
df.shape

(50000, 2)

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.shape

(49582, 2)

## Pre-processing

### 1. Converting to lowercase

In [9]:
df["review"] = df["review"].str.lower()

### 2. Removing the URLs

In [10]:
import re

# sample_text = "abc is the word, abc" # abc => xyz

# new_text = re.sub("abc", "xyz", sample_text)

In [11]:
def remove_urls(text):
    text = re.sub(r"http\S+" , "", text)  # (pattern, repl, string) eg - https://www.google.com
    return text
    
df["review"] = df["review"].apply(remove_urls)

### 3. Removing punctuations

In [12]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

In [13]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

### 4. Removing HTML

In [14]:
def remove_html(text):
    text = re.sub(r"<.*?>" , "", text)
    return text

df["review"] = df["review"].apply(remove_html)

### 5. Removing the Stopwords

In [15]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /usr/share/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [16]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [17]:
# sample_text = "I like coding in python!"
# tokens = word_tokenize(sample_text)

In [18]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [19]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

### 6. Stemming

In [20]:
# running -> run
# played -> play
# PorterStemming

from nltk.stem import PorterStemmer

In [21]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [22]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

### 7. Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [24]:
y = df["sentiment"]

In [25]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [26]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

## Dataset & Data Loaders

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [29]:
X_train.shape

(39665, 5000)

In [30]:
X_test.shape

(9917, 5000)

In [31]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [32]:
X_train = X_train.toarray()
X_test = X_test.toarray()

In [33]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [34]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

## Build our RNN

In [40]:
import torch.nn as nn
import torch.optim as optim
device =torch.device('cuda')

In [42]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        out, _ = self.rnn(x, h0) 
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [43]:
input_size = X_train.shape[1]
device =torch.device('cuda')
model = RNN(input_size).to(device)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

## Training the RNN

In [44]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        Xb,yb=Xb.to(device),yb.to(device)
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction
        
        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs.squeeze()) # (batch_size,) => probability

        loss = criterion(outputs, yb) # compute loss
        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch+1}/{epochs} and loss = {loss.item()}")

epoch = 1/10 and loss = 0.2591271698474884
epoch = 2/10 and loss = 0.19882932305335999
epoch = 3/10 and loss = 0.2452787458896637
epoch = 4/10 and loss = 0.21525982022285461
epoch = 5/10 and loss = 0.16082605719566345
epoch = 6/10 and loss = 0.2056598663330078
epoch = 7/10 and loss = 0.2854920029640198
epoch = 8/10 and loss = 0.423703670501709
epoch = 9/10 and loss = 0.23269277811050415
epoch = 10/10 and loss = 0.16983987390995026

In [45]:
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0
    
    for Xb, yb in test_loader:
        Xb,yb=Xb.to(device),yb.to(device)
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 85.83240899465564